# Generated by Django 4.1.4 on 2022-12-21 22:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='адресс местонахождения')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адресы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение 1')], verbose_name='инвентарный номер')),
                ('location', models.CharField(max_length=250, verbose_name='местонахождение по адресу')),
                ('room', models.CharField(max_length=150, verbose_name='помещение')),
                ('clear_name', models.CharField(max_length=100, verbose_name='понятное название')),
                ('brand_or_model', models.CharField(max_length=100, verbose_name='бренд / модель')),
                ('serial_number', models.CharField(max_length=100, verbose_name='серийный номер')),
                ('owner', models.CharField(max_length=150, verbose_name='за кем числиться')),
                ('image', models.ImageField(upload_to='items/images/', verbose_name='картинка')),
                ('remark', models.CharField(max_length=250, verbose_name='примечание')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.address', verbose_name='адресс местонахождения')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
                'ordering': ['id'],
            },
        ),
    ]
