# Generated by Django 4.1.4 on 2022-12-19 22:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение 1')], verbose_name='инвентарный номер')),
                ('location', models.CharField(max_length=250, verbose_name='местонахождение')),
                ('room', models.CharField(max_length=150, verbose_name='помещение')),
                ('clear_name', models.CharField(max_length=100, verbose_name='понятное название')),
                ('brand_or_model', models.CharField(max_length=100, verbose_name='бренд / модель')),
                ('serial_number', models.CharField(max_length=100, verbose_name='серийный номер')),
                ('owner', models.CharField(max_length=150, verbose_name='за кем числиться')),
                ('remark', models.CharField(max_length=250, verbose_name='примечание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='за кем числиться')),
            ],
        ),
    ]
