# Generated by Django 4.1.4 on 2022-12-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['id'], 'verbose_name': 'предмет', 'verbose_name_plural': 'предметы'},
        ),
    ]
