# Generated by Django 4.1.4 on 2022-12-19 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_items_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='адресс местонахождения')),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='location',
            field=models.CharField(max_length=250, verbose_name='местонахождение по адресу'),
        ),
        migrations.AddField(
            model_name='items',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.adress', verbose_name='адресс местонахождения'),
            preserve_default=False,
        ),
    ]
