# Generated by Django 4.1.4 on 2022-12-19 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_adress_alter_items_location_items_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['id'], 'verbose_name': 'адрес', 'verbose_name_plural': 'адресы'},
        ),
    ]
