# Generated by Django 4.1.4 on 2022-12-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_adress_address_alter_address_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default=1, upload_to='items/images/', verbose_name='картинка'),
            preserve_default=False,
        ),
    ]
